version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass joel_rocks
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  database:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=joel
      - POSTGRES_PASSWORD=is_awesome
      - POSTGRES_DB=joelhooks_db
    ports:
      - '5432:5432'
