# fly.toml file generated for falling-cloud-6728 on 2021-11-30T15:37:24-08:00

app = "falling-cloud-6728"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  CYPRESS_INSTALL_BINARY = "0"
  FLY = "true"
  HUSKY_SKIP_INSTALL = "1"
  NODE_ENV = "production"
  PORT = "8080"
  PRIMARY_REGION = "sea"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
